name: Pancake
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cancel-previous-runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  macos:
    needs: cancel-previous-runs
    name: macOS ${{ matrix.configure.tag }} (${{ matrix.build.compiler }})
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Esy
        run: yarn global add esy
      - name: Build PPX
        run: yarn build-ppx
