#!/usr/bin/env sh

# Get the directory of the script to work from.
DIR=$(dirname "$0")

if [ -f $DIR/ppx_src/_esy/default/build/default/.ppx/pancake/ppx.exe ]; then
    # Use the dev build
    $DIR/ppx_src/_esy/default/build/default/.ppx/pancake/ppx.exe --as-ppx $@
else
    echo "No build found" 
fi
