name: Pancake Build 
on:
  release:
    types: published

jobs:
  cancel-previous-runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build-osx:
    name: Build OSX PPX
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install esy
      run: yarn global add esy
    - name: Run Build
      run: yarn build-ppx
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: macos-ppx
        path: ppx_src/_esy/default/build/default/bin/bin.exe 

  build-linux:
    name: Build Linux PPX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install esy
      run: yarn global add esy
    - name: Run Build
      run: yarn build-ppx
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: linux-ppx
        path: ppx_src/_esy/default/build/default/bin/bin.exe 

  #npm-release:
    #name: NPM Release
    #runs-on: ubuntu-latest
    #if: github.event.action == 'published'
    #needs: build
    #steps:

      #- uses: actions/checkout@v2
        #with:
          #ref: ${{ github.ref }}

      #- uses: actions/setup-node@v1
        #with:
          #always-auth: true
          #registry-url: "https://registry.npmjs.org"

      #- env:
          #NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        #run: |
          #echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          #yarn publish
