name: Pancake
on:
  pull_request:
    types: [opened, synchronize]
  release:
    types: published

jobs:
  cancel-previous-runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Install esy
      run: yarn install --frozen-lockfile

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Run Build
      run: yarn build-ppx

    - name: Add OSX ppx
      run: mv ppx_src/_esy/default/build/default/bin/bin.exe ppx-osx.exe 

  #npm-release:
    #name: NPM Release
    #runs-on: ubuntu-latest
    #if: github.event.action == 'published'
    #needs: build
    #steps:

      #- uses: actions/checkout@v2
        #with:
          #ref: ${{ github.ref }}

      #- uses: actions/setup-node@v1
        #with:
          #always-auth: true
          #registry-url: "https://registry.npmjs.org"

      #- env:
          #NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        #run: |
          #echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          #yarn publish
