name: Pancake
on:
  release:
    types: published

jobs:
  build-lib:
    name: Build Lib
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install Dependencies
      run: yarn
    - name: Run Build
      run: yarn build

  build-ppx:
    name: Build PPX
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Install Esy
      run: yarn global add esy
    - name: Run Build
      run: yarn build-ppx
