name: Pancake PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-ppx:
    name: PR Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "5.1.0"
    - name: Install Dependencies
      run: make install
    - name: Test
      run: make test
